name: "Default environment variables"

on:
  push:

jobs:
  mainjob:
    name:"Print default environment variables"
    runs-on: ubuntu-latest

    steps:
    - name: print-values-of-env-vars
      run:
        echo "$GITHUB_REPOSITORY_OWNER"